name: Draft PDF
on:
  push:
    branches: [joss_submission]

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@v1.0
        with:
          journal: joss
          paper-path: joss/paper.md
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: joss/paper.pdf
